name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel

        # Instalar distutils correctamente
        sudo apt install -y python3-distutils

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK + Build-tools
      run: |
        sudo apt install -y unzip
        mkdir -p $HOME/.buildozer/android/platform

        # Descargar commandline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/.buildozer/android/platform
        mv $HOME/.buildozer/android/platform/cmdline-tools $HOME/.buildozer/android/platform/android-sdk

        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH

        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses

        # Instalar AIDL + plataforma Android 34
        yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

    - name: Build APK
      run: |
        buildozer android debug

